version: "3"

services:
    mars-robot-api:
        environment:
          - PORT=8081
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8081"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]